### PR TITLE
[FIX] The precrement operator of SeqAn iterators doesn't statisfy the (Weakly)Incrementable concept

### PR DESCRIPTION
**Pull request by marehr**
This was fixed by removing const from return type of operator++.

### CODE REVIEW

**Comment by marehr** [comment]
Not sure which is the base branch. Should I PR against master or develop?

**Comment by smehringer** [comment]
I think always against develop

**Comment by h-2** [comment]
Can you change this for pre-decrement, too?

**Comment by marehr** [comment]
> Can you change this for pre-decrement, too?

done

**Comment by marehr** [comment]
> Phew... Why do we return references at all? shouldn't preincrement return a copy? Is this function used anywhere?

If you do `++p` on an iterator, it is required that you give a reference back (see https://en.cppreference.com/w/cpp/named_req/InputIterator)

> 
> Either way, you would need to make the same change for predecrement no? As well as `+=`..

done 

> 
> Nice, `operator-` and `operator-=` are commented out laughing

yeah lucky me :grin:

**Pull request merged**
