### PR TITLE
[FIX] testcase for bam_file can't build if zlib is missing

### PR DESCRIPTION
**Pull request by marehr**

### CODE REVIEW

**Comment by rrahn** [comment]
Since you started this evil task. Can you please check what is broken there?

**Comment by marehr** [comment]
!rebuild

**Comment by rrahn** [comment]
So it seems that the compilation with msvc finally works but that there is a weird bug in the RnaRecord structure.
Can you have a look at this as well? I know ... but you opened it 😈 !!!

**Comment by marehr** [comment]
!rebuild

**Pull request merged**
