### PR TITLE
[FIXED-#2166] String and StringSet conversion

### PR DESCRIPTION
**Pull request by joergi-w**

### CODE REVIEW

**Comment by h-2** [comment]
Why did you keep the StringSet constructors as explicit and did not apply the same check as for Strings?

**Comment by joergi-w** [comment]
The `StringSet` constructors do not cause all the trouble we saw with the explicit `String` constructors, so I considered the stricter as the better solution here. Should I change them to the `enable_if` version anyway?

**Comment by h-2** [comment]
Yes, best be consistent.

**Comment by joergi-w** [comment]
The enable_if does not make sense here, because the String argument in the StringSet constructor is already restricted to TString, which is the String Type in the StringSet. So I just removed the explicit keyword.

**Pull request merged**
