### PR TITLE
[FIX] Make `begin` SFINAE friendly for concept checks

### PR DESCRIPTION
**Pull request by marehr**

### CODE REVIEW

**Comment by h-2** [comment]
I don't fully understand the problem. Why would you want to call begin on an iterator?

**Comment by smehringer** [comment]
@h-2 I think the concept check on an iterator will try to evaluate begin() on an iterator and as I understand @marehr's comment, the check causes a hard compiler error right now.

**Comment by h-2** [comment]
Sounds weird to me, but I'll merge it if it fixes something for someone :man_shrugging:

**Comment by marehr** [comment]
> @h-2 I think the concept check on an iterator will try to evaluate begin() on an iterator and as I understand @marehr's comment, the check causes a hard compiler error right now.

Exactly, @smehringer understands me :)

**Pull request merged**
