### PR TITLE
[FIXES-#2017] Disables simd feature for gcc < 5.0.0

### LINKED ISSUE #2017: severe performance issues of SIMD code with GCC 4.9
Something is  bugged in GCC 4.9 or in our SIMD code in relation to GCC 4.9.
Lambda run times with SIMD enabled are on average 10-15% better than without SIMD. This is true for GCC>=5 and clang.
For gcc-4.9 however the run-time **increases** by a factor of 2x to over 10x! I am not sure what that amount of slow-down depends on, it seems to just increase with the amout of SIMD that you are doing (in a non-linear fashion).

I have verified this with gcc-4.9.4 on FreeBSD and gcc-4.9.2 on Debian.

I propose 
* [ ] we deactivate SIMD on gcc-4.9 for now [ for 2.3.2 ?]
* [ ] we debug the problem if possible [ for 2.4.0 ?]

### PR DESCRIPTION
**Pull request by rrahn**
fixes #2017

### CODE REVIEW

**Comment by marehr** [comment]
Can we do that after my pull request? I changed the structure.

**Comment by rrahn** [comment]
@marehr well, no. Because this is a hotfix and your's is not. :godmode: :

**Comment by marehr** [comment]
Where is this a hotfix? This is completely undocumented code.

**Comment by rrahn** [comment]
But we can keep this on hold and first fix it for 2.4 I guess. Since we only put it here, as 2.3.2 is close to be released.

**Comment by rrahn** [comment]
@marehr can you then just add this to you PR. I'll close this issue then.

**Pull request closed without merging**
