### PR TITLE
[FIX] don't detect openmp on clang

### PR DESCRIPTION
**Pull request by h-2**

### CODE REVIEW

**Comment by esiragusa** [comment]
@h-2 We have (had?) nightly builds under clang/openmp. We used this: http://clang-omp.github.io.

**Comment by h-2** [comment]
i have fixed the previous build issues now, but test_parallel  still segfaults and nearly all our apps make clang crash during build:
https://llvm.org/bugs/show_bug.cgi?id=24674

This is fixed for 3.7.1, but since that hasn't shipped yet I propose deactivating clang for now. I will however update this pull, so that the build flag stuff works right, as soon as we reactivate it.

**Comment by h-2** [comment]
> @h-2 We have (had?) nightly builds under clang/openmp. We used this: http://clang-omp.github.io.

long time ago ;)

**Comment by esiragusa** [comment]
Is it only clang 3.7.0? Can't you deactivate only that version?

**Comment by h-2** [comment]
> Is it only clang 3.7.0? Can't you deactivate only that version?

Thats the plan, although I can't verify that 3.7.1 will work, because I don't have a svn version installed that is new enough.

**Comment by esiragusa** [comment]
I didn't see that one demo now fails to compile. See: http://cdash.seqan.de/viewBuildError.php?buildid=147471.

**Pull request merged**
