### PR TITLE
fix extensions (master)

### PR DESCRIPTION
**Pull request by h-2**
see #1037

### CODE REVIEW

**Comment by h-2** [comment]
@esiragusa Now some of the tests involving bam fail. I think the transparent decompression is not applied... do you have any quick thoughts on this?

**Comment by esiragusa** [comment]
Hey, in #1037 I meant to overload the FileFormat metafunction for the VirtualStream of SeqFile and remove BgzfFile from the list. In this way you disabled it for all file formats!

**Comment by esiragusa** [comment]
And, in my opinion, the name FileFormat is misleading! FileFormat of FormattedFile lists file formats (it's okay) but FileFormat of VirtualStreams lists stream encodings (maybe it should be called StreamFormat or similar).

**Comment by h-2** [comment]
> Hey, in #1037 I meant to overload the FileFormat metafunction for the VirtualStream of SeqFile and remove BgzfFile from the list. In this way you disabled it for all file formats!

Hm, shouldn't it be the other way around, that bzgf is especially enabled for some, but not in general?

**Comment by esiragusa** [comment]
I don't think so, bzgf is a general compression format (like bzip2).

There seems to be a bit of confusion with formats/extensions: we don't want to have fastq.bam but we might want to have fastq.bzgf (e.g. for parallel decompression or random seeks).

**Comment by h-2** [comment]
> I don't think so, bzgf is a general compression format (like bzip2).

I can find no documentation on this. Google barely yields any results and those that it does all point to BAM. 

But I can  overload FileFormat for SeqFile as suggested early on and maybe we can rediscuss this a later point.

**Comment by esiragusa** [comment]
Google doesn't help because I mistyped the name, it's BGZF! :tada:

**Comment by h-2** [comment]
ROFL, okay!

**Comment by h-2** [comment]
> And, in my opinion, the name FileFormat is misleading! FileFormat of FormattedFile lists file formats (it's okay) but FileFormat of VirtualStreams lists stream encodings (maybe it should be called StreamFormat or similar).

It all seems kind of confusing to me. I don't see how I can overload the compressed formats for any FormattedFile, since VirtualStream cannot be specialized for this.

We have different FormattedFiles which each have different Formats which each have different extensions and each extension has again multiple compressed versions. And the mechanisms for defining what is legal in the end are different for each layer of abstraction. Plus there is (nearly) no documentation -> I don't want to complain, but its really not nice.

Any hints for solving the current issue, i.e. not having the bgzf extensions added to SeqFormats?

Thanks!

**Comment by h-2** [comment]
And why is `getFileExtensions()` a member function of `FormattedFile`? It means that I can't overload it, otherwise I could sneak in a different CompressedFormats Taglist there...

I could overload `_getCompressionExtensions()` for SeqFormat and always ignore/replace the copmressionformats argument, but thats a hack at best.

**Comment by h-2** [comment]
Ok, I have an intermediate solution. First of all, I would like to say that I think Bgzf should just not define `.bam` as of its extensions. This should only every be defined by the bam-format. However it is apperently not easy to do with our IO-code, at least not for me.

The current solution does the following:
  * define one set of CompressedFileTypes with and one without Bgzf
  * the `getFileExtensions()` by default returns combinations without, but for `FormattedFile<Bam...` returns combinations with

This achieves the desired behaviour with minimal changes and is easy to adapt, once a more thorough solution should be developed.

@rrahn can you review?

**Comment by rrahn** [comment]
First of all, why should fasta.bgzf be a problem? Look here: http://blastedbio.blogspot.de/2011/11/bgzf-blocked-bigger-better-gzip.html
So biopython can do this on any type of file :v:
So in general as @esiragusa already mentioned, this is just another compression format.
So why all the hustle to get it off of other sequence file formats?

**Comment by rrahn** [comment]
So is the issue, that we don't have a compressed format called ```bgzf``` but only ```bam```?

**Comment by h-2** [comment]
> So is the issue, that we don't have a compressed format called bgzf but only bam?

The issue is that `.bam` is accepted as general extension for any bgzf'ed file. As discussed I will merge this and we can reevaluate the issue at a later point in #1037

**Pull request merged**
