### PR TITLE
Add version selector in API doc.

### LINKED ISSUE #724: Dox does not support switching between version.
@holtgrewe @bkahlert:
Please add functionality to switch between the versions of the documentation as is done for the readthedocs documentation.
There you can select another version for the current page (See lower left corner at the side bar, there is a small drop down menu). 
Who is gonna responsible for such things?

### PR DESCRIPTION
**Pull request by xenigmax**
You can add a version selector in API doc. by simply adding 
``` <script type="text/javascript" charset="utf-8" src="js/version.js"></script> ```
Check http://docs.seqan.de/seqan/master_version_test/ as an example.

To do that, I made a .php script in the documenation server.
- version.php : This will generate available versions in JSON format based on local directories.
Check http://docs.seqan.de/version.php

This will close #724.

### CODE REVIEW

**Comment by h-2** [comment]
LGTM! @rrahn can I merge?

**Comment by xenigmax** [comment]
@h-2, @rrhan suggested a better "UI" for this. I'm working on that.

I will make a PR again.

**Comment by rrahn** [comment]
@xenigmax Is this now ready?

**Comment by h-2** [comment]
@xenigmax @rrahn can this be merged?

**Comment by rrahn** [comment]
I don't know?

**Comment by xenigmax** [comment]
@h-2 @rrahn 

There is a Safari(Mac) specific problem. It's a HTML issue.
I will find a way to reproduce the situation and will fix it soon!

**Pull request merged**
