### PR TITLE
[FIX] Fixes the CTD support for the prefix file types #1172

### PR DESCRIPTION
**Pull request by temehi**
[FIX] Fixes the CTD support for the prefix file types
- Added new mimetypes for yara_indexer
- Adds the "any" extension (*) in case of prefix types (input/output)
- This fixes the issue #1172

### CODE REVIEW

**Comment by temehi** [comment]
@rrahn @h-2 @esiragusa can you guys merge this ASAP I need it for my next work.

**Comment by h-2** [comment]
@temehi I think it would be better to have a generic SA-Index or FM-Index type, not a "Yara"-type, as the endings are not specific to yara.
Altogether I still do not know why KNIME needs to know about this, though. None of the calling apps need to see these extensions, you always just use the base filename as argument, so I think it is completely unrelated to CTD, or not?

**Comment by temehi** [comment]
@h-2 do other indexers produce this extensions as well? If yes, I will make them an index type. that is not a problem. 

> so I think it is completely unrelated to CTD, or not? 

in order to connect two nodes you need to make sure that the output of one node is compatible to the input type of the second. in the case of input/output prefixes we need to make evrything compatable with everything... So NO it is related to CTD.

**Comment by esiragusa** [comment]
Looks good to me. However Yara's index adds two files .rid.concat and .rid.limits to the FMIndex files. These files store reference ids (sequence names).

**Comment by temehi** [comment]
@esiragusa you mean these two extensions are specific to yara? @h-2 do you have extensions specific to Lambda as well?

**Comment by esiragusa** [comment]
@temehi yes

**Comment by h-2** [comment]
>  @h-2 do you have extensions specific to Lambda as well?

Yes, I do. They depend on selected options, though. Is that a problem?

**Comment by temehi** [comment]
Not at all! all we have to do is register them. But we can do this latter when LAMBDA is KNIME ready. lol.. you know it's a big commitment?. .lol

**Comment by temehi** [comment]
@h-2 ping!  Is there still a problem not to merge this PR?

**Pull request merged**
