### PR TITLE
modified iterators and modview (again)

### PR DESCRIPTION
**Pull request by h-2**
some modview related fixes and new tests.

Don't commit yet, some more cleanup needed.

### CODE REVIEW

**Comment by h-2** [comment]
This is done from my POV, will commit later today if there are no objections.

**Comment by rrahn** [comment]
Please hold this until it is reviewed.

**Comment by h-2** [comment]
@rrahn yes, there are also outstanding build issues in the develop branch...

**Comment by h-2** [comment]
@holtgrewe please review 3215f13, see also the commit message. Thanks!

**Comment by h-2** [comment]
All remaining erros unrelated. @rrahn can you have a last look?

**Comment by rrahn** [comment]
lgtm!

**Pull request merged**
