### PR TITLE
Merge master to develop

### PR DESCRIPTION
**Pull request by rrahn**

### CODE REVIEW

**Comment by joshuak94** [comment]
@rrahn Travis went through!

**Comment by h-2** [comment]
What about the failed jenkins tests?

**Comment by rrahn** [comment]
rebuild

**Comment by rrahn** [comment]
rebuild

**Comment by rrahn** [comment]
rebuild

**Comment by rrahn** [comment]
Ok osx builds are green. Windows builds won't work, because our IT has restricted the access from external IP addresses. Which means we can't access the windows VMs from the Jenkins server 😢 
I will temporarily disable them until we have access again.

**Pull request merged**
