### PR TITLE
[NOP] Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by marehr**

### CODE REVIEW

**Comment by h-2** [comment]
Please make a PR against develop, too!

**Comment by marehr** [comment]
Cherry picking the commit, or merging the commit + master changes into the develope branch?

**Comment by h-2** [comment]
just pull from the same branch into develop. It's not ideal, but cherry-picking supposedly changes commit IDs...

**Comment by marehr** [comment]
Thats true, but the auto-merger of git is quite strong in finding cherry-picks..

Anyway, I will do a new pull request.

**Pull request merged**
