### PR TITLE
Fix travis CI

### PR DESCRIPTION
**Pull request by rrahn**
- Fixes issue with upgrading pip
- Uses apt install for clang++-3.5 and clang++-3.8
- Adds gcc6 to build matrix

### CODE REVIEW

**Comment by h-2** [comment]
you still exceed the time limit, I think you shouldnt add the line about "precise"...

**Comment by rrahn** [comment]
@h-2 quite possible. Let's see if it is fixed now.

**Comment by rrahn** [comment]
@h-2 great now it is using container based infrastructure but still caps the build at 50 min. Any idea?

**Comment by h-2** [comment]
@rrahn unfortunately not
reassigning, since I will be on vacation

**Comment by h-2** [comment]
Maybe the timeout is related to what is currently setup as the default, i.e. a PR update of the yml won't change this behaviour. I will merge this to verify this. If it doesn't help I think you need to contact travis support.

**Pull request merged**
