### PR TITLE
[DOC] Vcf header 'FORMAT' description

### PR DESCRIPTION
**Pull request by bricoletc**

### CODE REVIEW

**Comment by bricoletc** [comment]
Hi! Just happened to notice this while reading through the docs, I'm pretty sure that FORMAT tags for Vcf records should be described using FORMAT in the header, not ID

Thanks for your library!!

**Comment by rrahn** [comment]
>Hi! Just happened to notice this while reading through the docs, I'm pretty sure that FORMAT tags for Vcf records should be described using FORMAT in the header, not ID

That is certainly true. Many thanks for spotting and fixing this.

**Comment by smehringer** [comment]
@rrahn can Imerge this?

**Comment by smehringer** [comment]
@bricoletc Can you sign the clahub please?

**Comment by bricoletc** [comment]
Sorry, had not seen https://github.com/seqan/seqan/pull/2392#issuecomment-532062965, thanks for editing! I signed CLA

**Comment by rrahn** [comment]
I will fixup the broken CI stuff in another PR and then I will rerun the CI here. If it goes through we can merge it. Thanks for bearing with us this long.

**Comment by rrahn** [comment]
@bricoletc would it be possible to rebase this branch on current develop? Then the CI should turn green 🤞. Many thanks!

**Comment by rrahn** [comment]
@bricoletc thanks for rebasing. It seems, however, that not the latest develop branch was used? Can you verify this?

**Comment by bricoletc** [comment]
@rrahn you're absolutely right, sorry for the mistake :/ Rebased off fbb64f5a5 now.
Just wondering about the readthedocs, are you going to move them to seqan3?

**Comment by rrahn** [comment]
>sorry for the mistake

No problem!

>  Just wondering about the readthedocs, are you going to move them to seqan3?

We haven't planned for it in the near future. We started to track the tutorials within doxygen. IIRC there are converters from doxygen to readthedocs but we had no time to work on that yet. So at some point, once all the main features have been ported, we will rethink where to host the documentation. Of course we are happy about any help or contribution 😄

**Pull request merged**
