### PR TITLE
Snp_store

### PR DESCRIPTION
**Pull request by serosko**
Änderungen am SnpStore im Verlauf meiner Masterarbeit.

### CODE REVIEW

**Comment by h-2** [comment]
@serosko thanks for the PR!

But for it to be merged the following things still need to happen:
  1. the conflicts with the develop branch need to be resolved
  1. since the changes are big, some kind of summary would be good, e.g. which bugs problems were fixed; were any publicly documented interfaces changed?
  1. the commit messages should conform to our guidelines, i.e. everything should be prefixed by `[FIX]`, `[FEATURE]`, `[INTERNAL]` ...

I will also move through the code and look at syntax et cetera. In any case thanks for the changes!

**Comment by h-2** [comment]
Since you are doing large style changes, can you please just run uncrustify on the file with our config at util/uncrustify ?

**Comment by serosko** [comment]
Summary of changes:
- Some reformating for better complianc with Style-guide
- Some refactoring to make some function more atomic
- Changed output format from old format to VCF-4.2 specifications
- Added filter for variant quality (MAQ method) (default: 10)
- Changed filtering behavior s.t. the applied filters are listed in the VCF output and the variants are not just silently uncalled.
- Fixed behavior that led to some variants not being listed if the reference genotype is more likely
- Fixed Bug that lead to wrong calculation of a value used for -mec filter option in heterozygous SNPS.
- Changed default values of some filter options because they were to strict. 
- Made option "corrected-het" default if Boost is available.

**Comment by serosko** [comment]
Code has been uncrustifyed. Also Added missing CMakeList and updated/added Readme to reflect the changes. Checked out and merged with develop without conflicts. Pushed branch to my repository. Do I somehow have to update the pull request?

**Comment by h-2** [comment]
OK, that sounds good, but github still says that there are conflicts, can you look into this?

Also, can you fix the commit messages? I think it should be enough to do
```sh
git rebase --interactive 533bf41
```
And adapt the names.

Plus, your committer e-email is not known by github, can you add it in your profile so that the commits are associated with your account?

**Comment by h-2** [comment]
Any progress here? We really do appreciate the PR!
Assigning to @rrahn because I am on vacation.

**Comment by serosko** [comment]
I will shortly apply the suggested changes. It got delayed because I was/am on vacations.

----- Nachricht beantworten -----
Von: "Hannes Hauswedell" <notifications@github.com>
An: "seqan/seqan" <seqan@noreply.github.com>
Cc: "serosko" <SebastianRoskosch@web.de>, "Mention" <mention@noreply.github.com>
Betreff: [seqan/seqan] Snp_store (#1824)
Datum: Mo., Aug. 22, 2016 01:04

Any progress here? We really do appreciate the PR!

Assigning to @rrahn because I am on vacation.

&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.










{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/seqan/seqan","title":"seqan/seqan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/seqan/seqan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@h-2 in #1824: Any progress here? We really do appreciate the PR!\r\nAssigning to @rrahn because I am on vacation."}],"action":{"name":"View Pull Request","url":"https://github.com/seqan/seqan/pull/1824#issuecomment-241287980"}}}

**Comment by h-2** [comment]
@serosko Thanks for reformatting the commit messages. The snp_store test still fails though:
http://cdash.seqan.de/viewBuildError.php?buildid=194521
Please investigate this!

**Comment by h-2** [comment]
@serosko If you want this to be in the next release, please update the PR adressing the merge and test problems until wednesday night the latest.

**Comment by serosko** [comment]
If I read the error-log correctly, the app-test for snp_store fails, which is to be expected, since had to complete change the output format (now it's VCF). A whole new set of testing files would have to be generated. Furthermore, the tests have to consider, that the new output also includes the date it was generated at the beginning of the file.
I have no idea, why the CMakeList won't merge, especially because I only added one line.

**Comment by rrahn** [comment]
@serosko ping! 
If you want this going into the current release 2.3, than please address the open issues discussed by @h-2 until tomorrow. We will then freeze the repo for any new PR. You can rebase your branch with the current develop and then merge the conflicts manually. For the tests, you are right. If you change the output format, you have to generate new ones. There is how-to: http://seqan.readthedocs.io/en/develop/Infrastructure/Manage/WriteAppTests.html that might help with this task.

**Comment by serosko** [comment]
I tried rebasing again, but git tells me that everything is up to date. So I tried removing and adding the conflicting file, hoping that it works. I don't understand why it woul not work, because I only added a single line. I won't be abled to generate working test files because, the new output alway contains a timestamp, which will result in a failure of the test, since the timestamp of the gold-standard output will not be the same.

**Comment by rrahn** [comment]
@serosko ok, I will try to resolve it today.

**Comment by rrahn** [comment]
Replaced by #1961.

**Comment by serosko** [comment]
Made the changes suggested in #1961. Could not change behaviour of timestamp and could not generate new testing files.

**Pull request closed without merging**
