### PR TITLE
[DOC] Major restructuring of the manual.

### PR DESCRIPTION
**Pull request by rrahn**

### CODE REVIEW

**Comment by xenigmax** [comment]
Finally :+1:  Let's what happens. :)

**Comment by xenigmax** [comment]
Travis has restarted again. What's going on ...

**Comment by temehi** [comment]
It failed!

**Comment by temehi** [comment]
>
test_demo_tutorial_alignment_scoring_scheme_affine_dgs
test_demo_tutorial_alignment_align_assignment1

The standard output was not as expected! I thought I corrected this, in one of my pull requests.

**Comment by xenigmax** [comment]
I made a quick fix for this #1612

**Comment by esiragusa** [comment]
Can we delete this branch?

**Pull request merged**
