### PR TITLE
[DOC] Normalize some command line help

### PR DESCRIPTION
**Pull request by mr-c**
Will lead to better unix 'man' manual pages

### CODE REVIEW

**Comment by mr-c** [comment]
@h-2 Can this be merged?

**Comment by h-2** [comment]
@mr-c LGTM!
@rrahn Whats up with new Jenkins builds? Are these real errors or infrastructure problems?

**Comment by h-2** [comment]
rebuild

**Comment by h-2** [comment]
Thanks for the PR!

**Pull request merged**
