### PR TITLE
[COMMENT, DOC] Clean up mime_types and Added comment (develop)

### PR DESCRIPTION
**Pull request by temehi**
see #1554

### CODE REVIEW

**Comment by temehi** [comment]
@xenigmax could you merge this one too :+1:  same as #1554, to the develop branch.

**Comment by xenigmax** [comment]
@temehi 
Why this PR contains more commits than #1554 ?

**Comment by temehi** [comment]
The commits are not from me but those are merge commits, and can be ignored.

**Comment by xenigmax** [comment]
OK.. It seems master branch is ahead of develop now - which is not normal. :cry: 

Your modifications look good to me.

**Pull request merged**
