### PR TITLE
FX Tools: imported Dave's new tools

### PR DESCRIPTION
**Pull request by esiragusa**

### CODE REVIEW

**Comment by esiragusa** [comment]
@weese I reopened here your pull request - I'm sorry for messing up things! There seems to be problems with fx_read_depth, please have a look at http://cdash.seqan.de/buildSummary.php?buildid=122964.

**Comment by weese** [comment]
Ah, yes I fixed another thing in SeqAn's priority heap which must be slipped through my manually migrated PR. What is the current status of the SeqAn apps? Should they live outside or inside the seqan repo?

**Comment by esiragusa** [comment]
The apps will continue to live inside the seqan repository until we are able to setup an equally-good ci/nightly infrastructure. The apps as submodules had already caused various problems to our workflow... :-1:

**Comment by esiragusa** [comment]
We will have to think more wisely about that - your and @holtgrewe suggestions are welcome!

**Comment by esiragusa** [comment]
@weese your other pull requests are merged. You only have to add the missing commit about the priority queue... sorry for that!

PS see http://cdash.seqan.de/buildSummary.php?buildid=123217

**Comment by h-2** [comment]
@weese @esiragusa what is the state of this?

**Comment by esiragusa** [comment]
As discussed above...

**Comment by h-2** [comment]
@esiragusa @weese If this is not merged before 2.3.0 it will be closed.

**Pull request closed without merging**
