### PR TITLE
Major improvements to build system

### LINKED ISSUE #1349: supported platforms  [develop / 2.1.*]
- [x] FATAL CHECKS:
     -  MSVC < 2015
     - clang, gcc or icc don't provide `-std=c++11`

  - [x] WARNINGS:
     - clang < 3.5
     - gcc < 4.9
     - any icc or other unknown compilers

  - [x] remove dead code for old platforms
  - [x] Update all documentation (website, README.rst ...)
  - [x] throw out c-compiler detection (set language to CXX)

### PR DESCRIPTION
**Pull request by h-2**
* define all SeqAn projects to be C++-only, removing all detection of c compilers and related checks
  * deprecate the `SEQAN_FIND_DEPENDENCIES` system
    * just use `find_package()` throughout all tests and apps
    * all dependencies are still optional and have to be manually selected to be in the build
    * also deprecate `SEQAN_HAS*` for cmake variables (just use `*_FOUND` -- previous problems with this resolved) [compiler macros are unaffected]
    * remove custom versions of cmake-files and rely on system-wide versions for dependencies (OpenMP, zlib, bzip2)
    * update corresponding docs
  * stream-line the c++11 and c++14 detection so that `FindSeqAn` actually checks the compiler's defines and is not dependent on SeqAnBuildSystem; remove extra cmake-files

resolves #1349 #1368

### CODE REVIEW

**Comment by h-2** [comment]
@rrahn once this is thru, can you merge it?

**Comment by rrahn** [comment]
@h-2 please have a look to our tutorials regarding the SeqAn build system and the infrastructure to check if they need to be updated according to the changes made.

**Comment by h-2** [comment]
@rrhan I have, please see the list of changed files :)

**Comment by rrahn** [comment]
Ok good then.

**Pull request merged**
