### PR TITLE
[FIX] add overloads for const strings, as well

### PR DESCRIPTION
**Pull request by h-2**

### CODE REVIEW

**Comment by esiragusa** [comment]
But should't open() be non-const ref only and save() const ref only?

**Comment by h-2** [comment]
In theory yes, but since we have ridiculous global overloads for everything its usually advisable to overwrite both...
in this case however it seems to be ok ;) I will update it.

**Comment by esiragusa** [comment]
Which global overloads? There too, open() must be & only and save() const & only.

**Comment by h-2** [comment]
> Which global overloads?

I was referring to global overloads for things like insert and append which have versions for both const and non-const, although they shouldn't (I have removed many, but oh well). DIfferent topic.

**Comment by h-2** [comment]
@esiragusa can I merge this?

**Comment by esiragusa** [comment]
Well the diff is okay... but why do we need dummy open/save for modified strings?

**Comment by h-2** [comment]
Because the ModifiedString doesn't contain any data, so it shouldnt write any data!

**Comment by esiragusa** [comment]
Waait that's not true... :wink:

**Pull request merged**
