### PR TITLE
[FIX] Adds missing empty overload for std::list.

### PR DESCRIPTION
**Pull request by rrahn**

### CODE REVIEW

**Comment by h-2** [comment]
[i already merged the other stuff]

**Comment by rrahn** [comment]
I created another PR to resolve the merge conflicts between develop and master due to changes of files in master, which where already deleted in develop.
This PR causes one of the merge conflicts.
So please merge this before #1424

**Comment by rrahn** [comment]
Well the missing empty function is still a bug in 2.0.1 right.

**Comment by rrahn** [comment]
So that's this PR for.

**Pull request merged**
