### PR TITLE
Yara: fix static_cast regression

### PR DESCRIPTION
**Pull request by esiragusa**
@h-2 fyi #1444 broke yara... please merge this one.

### CODE REVIEW

**Comment by esiragusa** [comment]
@h-2 @rrahn please merge asap

**Comment by h-2** [comment]
@esiragusa Have you verified that this produces no warnings with GCC and Clang, on 32bit and 64bit, each?

**Comment by esiragusa** [comment]
It's correct now, have a look at the types...

**Comment by h-2** [comment]
You are not casting on the mateLength, are you sure this doesn't cause problems on 32bit, i.e. have you *tested* on clang and gcc with -m32 ? Because we have already "fixed" these two lines three times now, I would like this to be the final fix :wink:

**Comment by esiragusa** [comment]
Why don't you add 32 bit tests on travis? :wink:

**Comment by h-2** [comment]
> Why don't you add 32 bit tests on travis? :wink:

Thats actually a good idea for the future. For now: have you done the tests?

**Comment by esiragusa** [comment]
Sure it works on my mac... can you please merge it? Thanks.

**Pull request merged**
