### PR TITLE
feature/bam2fa

### PR DESCRIPTION
**Pull request by sproft**
added feature read BAM file as fasta or fastq

### CODE REVIEW

**Comment by h-2** [comment]
Thanks for the work on this, it already looks pretty good!

1) I think it would make more sense to move the addtions into an extra file `seq_io/sam_bam.h` and not put into the bam_io directory. That would be in line with the conceptual use case "reading sequences" rather than the technical implementation "both files are bam".

2)  Also it should work with a `SeqFileIn` / `SeqFileOut` to stay consistent with our interfaces.

3) Is there code for writing, as well? If not, do you guys have time to look at it? If not, could you have a look @temehi ?

4) It seems the stashing of commits didn't yet work properly, could you try that again?

@rrahn, what do you think?

**Comment by abadd0n** [comment]
to 1): sure we can move it to the another place
to 2): there is readRecord function that works with SeqFileIn and writeRecord that works with SeqFileOut already
to 3): one can use writeRecord function that alredy exists to write sequences to a file.
to 4): unfortunately we are not very familiar with stashing commits in git. Probably we will need some help with this one.

**Comment by h-2** [comment]
@abadd0n 

* Your tests still fails, please investigate. [Click on details for continuous integration]
* You need to sign our new Contributor License Agreement [Click on details beside clahub] IMPORTANT: make sure that all your commits are actually assigned to one of your user accounts. You can also add multiple e-mail addresses to your account

> to 1): sure we can move it to the another place

ok!

> to 2): there is readRecord function that works with SeqFileIn and writeRecord that works with SeqFileOut already

Yes, but not with bam files! That's the point: the bam **sequence io** should not be part of `BamFileIn`, but should be part of `SeqFileIn`.  If this not clear you need to discuss it again with @rrahn and/or @temehi.

> to 3): one can use writeRecord function that alredy exists to write sequences to a file.

But not into a bamfile, or am I missing something?

> to 4): unfortunately we are not very familiar with stashing commits in git. Probably we will need some help with this one.

You can come to any of our offices, preferably @cpockrandt's or @marehr's as they know a lot about git. 

Thanks for your work on this!

**Comment by rrahn** [comment]
@h-2 What is the point of writing a SeqFile into a BAM file. 
If people want to compress the files, they can do it already
But having a BamFile just to store sequence information doesn't really make sense to me?
Where is the advantage?
I agree, that we can use a bam file as if it is a sequence file. Though it is a alignment file and should not be used to simply store sequences, should it?
However, I think we can discuss this internally and add possible interfaces later. So the work here should be done with solely reading from BAM files.

**Comment by h-2** [comment]
@rrahn Please see the original feature request #712 which explicitly was as "SeqFile". Or google "fastqtosam" "fastq2bam" "fastq convert bam" to see that this is the actual used case used by research groups and companies.
I don't see any use for the current implementation, in fact I argue strongly against mixing sequence IO and align file IO.

**Comment by temehi** [comment]
@sproft @abadd0n can you read me?

If you do, I would like to meet with you guys this week, if possible? I want to discuss with you how we stash your commits and merge your PR.

**Comment by abadd0n** [comment]
Hi @temehi, unfortunately, we are a bit busy this week. How about we meet on Tuesday next week?

**Comment by h-2** [comment]
@temehi We won't release tomorrow, but we definitely will release next week. Can you work on this issue yourself? Otherwise I fear it won't be done in time for the release... Thanks!

**Comment by h-2** [comment]
@temehi what is the state here? Did you meet with @abadd0n ? Did you work on this any further?

**Comment by temehi** [comment]
@h-2 I didn't meet with @abadd0n. I am working on it but I am afraid it won't be ready for the release.

**Comment by sproft** [comment]
@temehi @h-2 Hi, @abadd0n and I are still uncertain as to what we should have done, as we hadn't yet received a meeting date to discuss our work. Is there anything we can do at this point to make the release go as smoothly as possible?

**Comment by h-2** [comment]
@sproft @temehi No problem, it's just that we have to move to the next release now.

**Comment by h-2** [comment]
@temehi @sproft @abadd0n  Please discuss and update this PR asap! The next release is due very soon, and I really don't want to move this to the next release again, especially considering that it will take much longer until the next release.

**Comment by temehi** [comment]
closed in favor of #1920

**Pull request closed without merging**
