### PR TITLE
[FIX] da padding-view

### PR DESCRIPTION
**Pull request by h-2**
Can a get a re---view? :notes:

### CODE REVIEW

**Comment by h-2** [comment]
> what about the CI failure?

Unrelated, it's the manual which definitely didn't touch.

**Comment by h-2** [comment]
Can I merge it?

**Comment by smehringer** [comment]
@rrahn Didn't you fix the manual builds?

**Comment by rrahn** [comment]
@smehringer it is not yet merged. I made the last commit for the changelog. once this is through I merge and the other PRs can be rebased.

**Comment by rrahn** [comment]
ok this can now be rebased on develop and should not fail anymore.

**Comment by h-2** [comment]
Merging this since you both approved and I just did the rebase (And it fixed the manual builds).

**Pull request merged**
