### PR TITLE
[FIX] change CPACK_GENERATOR on windows & change maintainer in deb packaging

### PR DESCRIPTION
**Pull request by xenigmax**
This fix is based on @h-2  's suggestion (https://github.com/seqan/seqan/issues/1809).

I would like to ask you to consider two things before merging.

1. Dependency & license
Unlike CPACK_NSIS, CPACK_WIX depends on wixtoolset. (http://wixtoolset.org/releases/)
So a user has to install wixtoolset before using this.
wixtoolset uses Microsoft Reciprocal License (MS-RL). http://wixtoolset.org/about/license/
I'm not sure whether it's OK or not.

2. LICENSE file format
LICENSE file must be provided with ".txt" extension in UTF-8. Or .rtf must be provided. This is a mandatory information. https://cmake.org/cmake/help/v3.1/module/CPackWIX.html
All the apps that do not contain .txt(UTF-8) or .rtf can't ship their license to the package.

Regarding 2, we have to change LICENSE file to **UTF-8** with **.txt** extension. (LICENSE.txt)
But I don't know the consequences of this change in other systems.
> kjk@giraffe:~/work/seqan$ file -bi LICENSE 
> text/plain; charset=us-ascii

Or we can provide another file - LICENSE.rtf.

Let me know your preference. Then I will change them accordingly.

### CODE REVIEW

**Comment by h-2** [comment]
> Dependency & license
> Unlike CPACK_NSIS, CPACK_WIX depends on wixtoolset. (http://wixtoolset.org/releases/)
> So a user has to install wixtoolset before using this.

Are you sure about this? I think it only needs to be available on the system that generates the installer, not on the target system. Can you check this?

> wixtoolset uses Microsoft Reciprocal License (MS-RL). http://wixtoolset.org/about/license/
> I'm not sure whether it's OK or not.

It's approved as a Free and Open Source license and it doesn't affect the license of our software so it's ok.

> Regarding 2, we have to change LICENSE file to UTF-8 with .txt extension. (LICENSE.txt)
> But I don't know the consequences of this change in other systems.

The encoding is irrelevant here. Regarding the extension, I don't want to change it for this little thing. Can you have CMake just copy `LICENSE`  to ` LICENSE.txt` in the build directory and then add that? [this would have to be done as part of seqan_configure_cpack_app]

**Comment by xenigmax** [comment]
@h-2 .

About the installer I tested it in Klette and got a mesaage like "cannot find wix".
This was resolved after I installed the toolchian and added the path of binaries to the system variables.

I also tried to copy LICENSE to LICENSE.txt and it gave me errors and it couldn't produce the package.
According to the link ..
"If CPACK_RESOURCE_FILE_LICENSE has an .txt extension it is implicitly converted to RTF by the WiX Generator. The expected encoding of the .txt file is UTF-8."
So I thought that it should be utf-8.
May I try this with utf-8?

**Comment by xenigmax** [comment]
I tried utf-8/.rtf but none of them worked.
The problem was not about encoding as you said.
It was about a path problem.  So It will ship license like before by copying them to .txt.
I will update PR about this.

But.. I have another issue. I realized a warning that I ignored before.
**EXEC : CPack warning : CPACK_WIX_UPGRADE_GUID implicitly set to 99EFC039-2326-44AB-BFDC-AA240BD79768 .** 
So it sounds like we have to set GUID for all apps if we don't want to see this.
Do you want to remove this? 
If so, how do you wish to set and maintain this?

**Comment by xenigmax** [comment]
image

**Comment by h-2** [comment]
> So it sounds like we have to set GUID for all apps if we don't want to see this.
> Do you want to set this?
> If so, how do you wish to set and maintain this?

I have no clue what you are talking about :sweat_smile: can you explain it?

**Comment by xenigmax** [comment]
OK. Here is the screenshot. There is a warning message (yellow).
We should provide GUID to WIX or it generate them randomly with that warning message.

And.. Since GUID has to be unique by definition, we have to provide different GUIDs for all apps if we decide to provide them. That's what I'm asking.

Please feel free to let me know if I misunderstood something.


screenshot from 2016-11-04 14 19 42

**Comment by xenigmax** [comment]
https://cmake.org/cmake/help/v3.0/module/CPackWIX.html
Windows uses it for checking pre-existing installation or replacing existing installations.
So it has to be maintained by us in theory..

**Comment by h-2** [comment]
@xenigmax let's ignore the warning for now and take pre-generated GUIDs...

**Comment by h-2** [comment]
@xenigmax are there open TODOs for this PR? What about the renaming of the license file?

**Comment by h-2** [comment]
@xenigmax ping

**Comment by rrahn** [comment]
@xenigmax ping

**Comment by xenigmax** [comment]
@h-2 , @rrahn  I've updated it and tested it on Klette.

**Pull request merged**
