### PR TITLE
[FIX] Actually use command line option seed in simulateGenome

### LINKED ISSUE #2452: mason_genome ignores --seed option
The program `mason_genome` has a command line option `--seed` to set the seed for the internal random generator. Extraction from the help:
```
-s, --seed INTEGER
      The seed to use for the random number generator. Default: 0.
```
Internally, this option is ignored and the seed is set to a hardcoded value instead.
From [simulate_genome.cpp](https://github.com/seqan/seqan/blob/master/apps/mason2/simulate_genome.cpp), lines 48-51:
```cpp
// Initialize std generator and distribution
std::mt19937 generator(42); // seed 100
std::uniform_real_distribution<double> distribution(0, 1);
auto randomNumber = std::bind ( distribution, generator );
```
The program produces the exact same sequences everytime it is called. The `--seed` option is misleading, because a different seed is expected to lead to a different result.

### PR DESCRIPTION
**Pull request by eseiler**
Supersedes https://github.com/seqan/seqan/pull/2453

Fixes  #2452

---

> APP Test have different output now!
> 
> mason_genome -l 1000 -o /tmp/tmp29e48tkb/genome.test1.fasta FAILED
> 
> Comparing /home/runner/work/seqan/seqan/seqan/apps/mason2/tests/genome.test1.stdout against /tmp/tmp29e48tkb/genome.test1.stdout
> 
> ```diff
> @@ -5,7 +5,7 @@
> 
>  
>  VERBOSITY  	1
>  
> -SEED       	0
> +SEED       	42
> Errors while running CTest
>  
>  OUTPUT FILE	genome.test1.fasta
>  CONTIG LENS	1000
> ```
> 
> This seems to be expected, because the default is now seed = 42.
> 
> mason_genome -s 1 -l 1000 -l 100 -o /tmp/tmp29e48tkb/genome.test2.fasta FAILED
> 
> Comparing /home/runner/work/seqan/seqan/seqan/apps/mason2/tests/genome.test2.fasta against /tmp/tmp29e48tkb/genome.test2.fasta
> 
> ```diff
> @@ -1,19 +1,19 @@
> 
>  >1
> -TATGCACCAGAGTATGGAAGCATAAGCTCTGCATGCAAAGGTACATCAGATCCTGCGGTTGGGTGCCAAC
> -CCAAGTGTGTTCACGGGCGCTTGACAGACATCGGAGGATGGTGCACACTCACTCGACCAGCGCAAAGCAC
> -AGGATCTCACGGGCGGACATCTCTTAGGTCAGTCATCGTGGAGGAATGCTTGTACGTTCTTTTGGCTTCC
> -CCTAACACGGCGGGCGTCTCCGGTACGTATCCTGTCGGTACACCCCTTAAGCCCCTAGGCCCGAAGAACA
> -TAGCGCATTTCACGCTCTCTACGAATGACCGCAACGATCAAATGGGCGAGAACAACTAATTCCGATTCAT
> -GGGGTTTGTGGATTGTGACACAGCGCGCCCGCTACTGCGGGACGTGAGGACGCCCAATTCTGCCAAGGAT
> -TATTTAGGGTGTTTCACTAGAGTTATGCGCCGACCCCGGTTGGACCAGCTTGCATTCGAAACTGCGTTAC
> -ACAGCACCCCACCGCAATCGTATGACTCTCGCTGAAAAAGGGTGGTCAACCATTACACCTCTTATGCCTG
> -TTGTGGGAGGCTCGGTCTTAAGCAGCGCGCGAGCTGTGATCCAGGCTACCACGGACATAGTGTATGGAAA
> -GTGATCCAGAGTAGACCCGCGGGGGCCTGACCTAACCTATATAAGTTGTATCGTGGCTATGAGGGTAGTC
> -GCCGGAGAAAACGTATGCTTACTGATTTTTAAGTCGGCGTGGCGCCGAAGCCGGATCGGTTGTAAGCTAG
> -CCGGGCCTAGGGGTTCACCGTAACGGATTAGTCAAATTAAAATCCAGCGATGACTTCCTGATAGAACTCA
> -AGTCGTGACCCCTCCGCTGCGGGCCTACATCTGTTTTCGCAGGCGTGGTTGTTTACCAGGTATGGTGCTC
> -ATCTCTATTAGTCACGGGCAGCATGGTGTCACCGAACCGCGCGTCTCCTAATATCTGGTCTACCGATTTA
> -GCCCCGGCAAATAACTTTGG
> +TTATACCGTTCGCAGTCCTTGTAGTTTCAGGGCACATCAGGCCAACATAGATTCGGGTCAGTCGTAATAT
> +GCTCGGCGGAGGCTCTTACATACTCTTCTAGAGCTCCTGACGACAGAAGACAGACATCAAGCCTCGGCTC
> +CCATTTGAGACCCAAATCAGCATTTGATTCGAAGATCATAAAACAATGTGCGGGAGCGTCTAATCAACTC
> +GACAGACTCCAGTGCCTAATCCGATCTAATATGAGAAACGTTCAAACCGGAATTACCCAAGAGACGCAAA
> +TTGACGTAAACAATGTGAACTAGAGTCTTAGCACCCAGGAAGCTTAAGAGTAATGCCACAGAGCAGTCGG
> +TCCAGTGGACTCGCTATGTCTGGTCGTCCTGCCCAGTATCGCCAAAGTTAGCGACAGGCCTACCGTCTGA
> +GGGGGCTTCTTGGATTTGAGGGACTTGGAGTGGTGCTGGCTTTGGCTTGTATAATCCGACTTGCTCCTAT
> +TGATATGCGACCATATACATCCCAATAGTACACTGGAATCGTCAAGACTTAGCGCACTACGACTAAGTCC
> +TTCTGTGATACGGCTACTGAAAAGCGCATCTAAAGCCGATGGAGGGGACCGAAACTCTGCCCACTTTTCT
> +ACATCTGCAAATGCGAGTGGTTGTTTGTAGGCCCGTTCTTCGGAGTCACATGATCAGGCAGCGGACTAAA
> +AGTACAGGCCCTCGGCCATAAATTTCCGTTAAGTGTTGAGGACTAACGTGGTGCAGGACGTTAGAGAAAA
> +TACAGACTTTGAACGCCCCGAGAACGATACTTAGGCCTCACCCGTTTGACGACGGAGAACGAGTATTTCG
> +GTTGGCAGGATTGAATGACGGTGACCCCCAATTAGTGGAAAATATGCAAAATAGCGGTGACGTAATTTGT
> +ACCAGTCACACGCACGGTACGTTCCCAAATTTATACGGCCTCGCCCTTGCATTGGGCTCTCCAACCGCCT
> +TAAACATCAGCCGGATCTTA
>  >2
> -ATTGTGGTTGGAGAGTGCCAGAACTGACGGGCGCTGCCGTGGGGCTCCTAACTAAAAACGCCACGGACCT
> -GGCTAACATTCGTTGTTGACTATAACATTT
> +CACAGGTCGTCGACTAGTTCGAGTTCCTCACGACCGCTGACCCTTTGACTTGCGGGCACCGGTGGTGTCT
> +GACGGACAGAGCCGGGTCCTTAGCGGCTGC
> ```
> 
> This seems to be expected, because the seed = 1 overrides the default seed = 42.

I left the default at 0 but checked that the original result (genome.test1.fasta) still worked when passed `-s 42`

### CODE REVIEW

**Review by marehr — APPROVED** [review]
I would have kept seed = 42, to have the same results. But we already messed this up 5 years ago. So we can change the outout again xD

**Comment by eseiler** [comment]
> I would have kept seed = 42, to have the same results. But we already messed this up 5 years ago. So we can change the outout again xD

One file needs to be changed, no?
Both files very generated with 42 as seed.
The intent was to test default seed and custom seed, so no matter what, I need to change something.

Or was it about that the behavior was seed=42 but now it is 0 (as always documented).

For continuity, 42 would be better..

**Comment by marehr** [comment]
I was just thinking that some apps might have used mason with a fixed seed, but now get different results, but we broke seeded results years ago. See here: https://github.com/seqan/seqan/commit/e332863e05cbd2a55738a9a5dcb2deaae41e9e5d#diff-bc5accb6b3fad5250037fbb3092daf37cd683c5053ac5f17d643ec08b179bd1bL48

**Comment by marehr** [comment]
So either seeding was used (which had no effect, so using it now changes result), or seeding was not used (current patch changes result).

Either way, since we broke re-producible behaviour years ago, I don't have any strong feelings to prefer 42 over 0.

**Comment by eseiler** [comment]
I set the default seed to `42` to reduce breakage :)

**Pull request merged**
