### PR TITLE
Reworked and restructured the workflow tutorials

### PR DESCRIPTION
**Pull request by temehi**
Reworked and restructured the workflow tutorials.

If possible, please review for typos and grammar.

### CODE REVIEW

**Comment by h-2** [comment]
@temehi please make sure that building the manual doesn't fail!

**Comment by temehi** [comment]
@h-2 That is because the base branch is failing to build. :innocent: 

The current seqan:feature/manual/restructure branch doesn't build without the error:

`... seqan/manual/source/Tutorial/DataStructures/Indices/StringIndices.rst:8: ERROR: Referencing unknown dox item BidirectionalIndex.`

**Comment by h-2** [comment]
@cpockrandt This would be your fault then! Can you please fix this asap, so we can assess the other PRs correctly? Thanks!

**Comment by cpockrandt** [comment]
Oops, something went terribly wrong - I think I messed up my git repo, I'll fix it asap!

Sorry :/

**Comment by cpockrandt** [comment]
Should be fixed with #1527. Let's see what travis thinks about that :smiley_cat:

**Pull request merged**
