### PR TITLE
fix read only index reading

### PR DESCRIPTION
**Pull request by h-2**
this actually just fixes read only reading of numbers, but apparently that was the only thing broken.

### CODE REVIEW

**Comment by esiragusa** [comment]
Oh this would be a hotfix for master.

**Comment by h-2** [comment]
the branch is from master -.-

**Comment by esiragusa** [comment]
You can cherry pick your commit into a hotfix branch based on master.

**Comment by h-2** [comment]
I know... I will keep this open to see if the tests pass so we can merge quicker

**Comment by h-2** [comment]
wow, it breaks everything. @esiragusa can you fix the branches issue? Then I will try to fix this again...

**Comment by h-2** [comment]
superseded by new pulls

**Pull request closed without merging**
