### PR TITLE
Fix/how to scoring matrix

### PR DESCRIPTION
**Pull request by cpockrandt**

### CODE REVIEW

**Comment by esiragusa** [comment]
The test test_demo_howto_scores_load_score failed. In case you can have a look into cdash.

**Comment by cpockrandt** [comment]
Works as soon as #1197 is merged (otherwise getAbsolutePath() is not defined)

**Comment by esiragusa** [comment]
@cpockrandt Could you please rebase this branch on the latest master? This PR should get automatically rebuilt so we will see if it works. Thanks.

**Comment by esiragusa** [comment]
@cpockrandt oh I think you did the wrong rebase!

**Pull request merged**
