### PR TITLE
Corrected download link

### PR DESCRIPTION
**Pull request by martinjvickers**
Originally pointing to a SAM file.

### CODE REVIEW

**Comment by xenigmax** [comment]
What is the motivation behind this? 
The links are broken.

**Comment by martinjvickers** [comment]
This tutorial is asking the user to run an example on a GTF file, but the link was pointing to a SAM file also hosted on the same FTP site as the GTF file.

http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Store/GenomeAnnotations.html#assignment-4

> 5 Test your program also on large data, e.g. the annotation of the mouse genome sim40mio_onlyY.sam.zip (don’t forget to unzip first).

**Comment by xenigmax** [comment]
Ah.. I see. You are correct. LGTM.

**Comment by h-2** [comment]
@martinjvickers Thank you for the PR!

**Comment by h-2** [comment]
but can you please recreate the PR against the develop branch? We only merge things to master that are regressions and/or sever problems. All regular bug-fixes and features go to develop!

**Comment by martinjvickers** [comment]
@h-2 I've recreated the PR

**Pull request closed without merging**
