### PR TITLE
[FIXED-#2104] Fixes sanitiser issue with StreamBuffer implementation.

### LINKED ISSUE #2104: Null pointer in iter_stream.h
Dear all, 

There seems to be an issue with the casting in iter_stream.h.

When applying the following patch:

```
--- seqan-seqan-v2.3.2/include/seqan/stream/iter_stream.h
+++ seqan-seqan-v2.3.2/include/seqan/stream/iter_stream.h
@@ -240,8 +240,9 @@
     {}
 
     Iter(TIStream & stream) :
-        streamBuf(static_cast<StreamBuffer<TValue> *>(stream.rdbuf()))
+        streamBuf(dynamic_cast<StreamBuffer<TValue> *>(stream.rdbuf()))
     {
+        printf("streamBuf: %p\n", streamBuf);
         stream.exceptions(std::ios_base::badbit);
     }
 
```

example 
```seqan/demos/tutorial/sam_and_bam_io/example1.cpp```
 will throw 
```streamBuf: (nil)```

Best,
Jochen

### PR DESCRIPTION
**Pull request by rrahn**
fixes #2104

### CODE REVIEW

**Comment by h-2** [comment]
This is because of member type definition? Can't we get around the entire casting by using some clever metafunctions that do the necessary inheriting and exposing of the types?

**Comment by h-2** [comment]
We agreed that this was done, right? Shall I merge?

**Comment by rrahn** [comment]
Jupp

**Comment by h-2** [comment]
windows CI still expected to be broken?

**Comment by rrahn** [comment]
Well, yes and no. Builds actually run but Jenkins frequently breaks or the ssh connection or whatever. But we need to rely on the nightlies unfortunately.

**Pull request merged**
