### PR TITLE
Fix/gustaf readme

### PR DESCRIPTION
**Pull request by ktrappe**
Created new file Readme.md. Left the old Readme file as it contains more details and file specifications.

### CODE REVIEW

**Comment by esiragusa** [comment]
Please, convert your readme to rst (you can use http://pandoc.org/try/), rename it as README.rst and add this line to your CMakeLists.txt https://github.com/seqan/seqan/blob/master/apps/yara/CMakeLists.txt#L192

**Comment by esiragusa** [comment]
Is this a hotfix? If so, you have to apply it to master.

**Comment by ktrappe** [comment]
Why does it have to be rst? Because of the build error?
It is not necessarily a hotfix (it's a readme after all), can I still apply it to master?

**Comment by esiragusa** [comment]
@ktrappe it's better to apply this as a hotfix, so master/develop won't diverge for your app.
@h-2 Then .md or .rst? Let's decide so that @ktrappe knows what to do...

**Comment by esiragusa** [comment]
Closed in favor of #1281, #1282.

**Pull request closed without merging**
