### PR TITLE
[FEATURE] Parallel DP

### PR DESCRIPTION
**Pull request by rrahn**
supersedes #2118

### CODE REVIEW

**Comment by rrahn** [comment]
Please do not merge yet.

**Comment by marehr** [comment]
my avx512 files are missing, right?

**Comment by rrahn** [comment]
Yes, but I think I have somewhere the path lying around.
We should add it as a separate PR.

**Comment by h-2** [comment]
@rrahn I will merge if travis passes, ok?

**Comment by h-2** [comment]
The branch still errors out on g++7 (before timing out): http://cdash.seqan.de/viewBuildError.php?buildid=254204

I have restarted the hung build on newest clang.

**Comment by rrahn** [comment]
yeha!!!

**Pull request merged**
