### PR TITLE
[DOC] Updated comment in tutorial (wrong AminoAcid conversion)

### PR DESCRIPTION
**Pull request by cpockrandt**
The AminoAcid table probably changed at some time :grin:

### CODE REVIEW

**Comment by smehringer** [comment]
Suggestion: 
I think we should not comment the expected output in the cpp file but append the stdout file at the end, like in many other examples. (The output looks like this: .. includefrags:: a_first_example.stdout)

This way we avoid problems like this.

**Comment by cpockrandt** [comment]
There are alreads *.stdout files. Then we should remove all comments that contain output to avoid differences in the future. What do you think @smehringer?

**Comment by smehringer** [comment]
Yes, that's just what I meant. 😆

**Comment by cpockrandt** [comment]
:grin: :grin: :grin: 

@smehringer Better now? :)

**Pull request merged**
