### PR TITLE
[FEATURE] Tabix index

### PR DESCRIPTION
**Pull request by weese**
I've finished a first version of tabix support which in conjunction with any chromosomal file format, e.g. VCF allows range queries on the file itself. To use the tabix index one has to compress the tab-delimited text file with bgzip (.gz) and index it with tabix (.gz.tbi).

I added a simple demo to show how it works.

```
./bin/demo_tabix_io_tabix_vcf ~/Development/healthplatform/data/gen/NA12878.vcf.gz chr1 10000 30000
10056	A	AC
10145	AC	A
10176	A	AC
10229	AC	A,AN
10326	T	C
10348	CCCTA	C,CCCTAA
10388	AC	A,AN
10395	AC	A
10438	AC	A
10468	C	G
10615	CCGCCGTTGCAAAGGCGCGCCG	C
10777	C	G
10972	T	A
14698	C	G
14906	A	G
14929	A	G
15210	T	G
15273	A	T
16013	C	T
16067	T	C
16102	T	G
16377	T	C
17384	G	A
17406	G	A
20244	G	A
20303	G	C
20466	C	T
28197	A	T
28325	GT	G
28353	C	T
28375	G	A
28562	A	G
28588	T	TTTGG
28862	C	A
```

Limitations:
 * the tbi index must be created with the distinct tabix tool (Heng Li)
 * if SAM with Tabix should be supported (actually we would recommend indexed BAM) one has to adapt ```_readTabixRecord``` to use the CIGAR to compute posEnd
 * to support all other tab-seperated chromosomal formats, e.g. BED, GFF, ..., one has to register bed.gz and gff.gz, ... as BGZF file extensions (which on the other hand forbids to use non-seekable standard gzip compressed files, they will be not recognized by their extension anymore)

### CODE REVIEW

**Comment by holtgrewe** [comment]
:+1:, bonus points for switching from MMap files to `std::fstream` in `FaiIndex`.

Note: `readRawPod` is undocumented, would you mind adding API documentation for it in this PR?

**Comment by esiragusa** [comment]
@weese could you please add that small demo example as a test?

**Comment by weese** [comment]
@esiragusa I just added the test

**Comment by weese** [comment]
Can this be merged? If yes and we merge it, #868 could be reopened which then should include only (and all) fx-tools related commits.

**Comment by esiragusa** [comment]
@weese okay i will rewind your branch and merge

**Comment by weese** [comment]
Ok thanks, sorry haven't seen that its not mergable.

**Pull request closed without merging**
