### PR TITLE
[FIX] ambiguous calls to std::empty/seqan::empty to allow building with -std=c++1z/-std=c++17

### PR DESCRIPTION
**Pull request by marehr**

### CODE REVIEW

**Comment by h-2** [comment]
Looks good, but let's wait for travis!
Could you (ina separate PR) replace the gcc-6 entry in travis by a gcc-7 entry that includes `-std=c++17`? Because right now the changes of this PR are not checked...

Thanks!

**Comment by marehr** [comment]
I tried building our test cases with `-std=c++17` locally and I had some more issues, so this will be the first patch for a series of other fixes.

Primarily those did not run:
```
	 73 - test_test_journaled_string_tree (Not Run)
	 75 - test_journaled_string_tree_traverser (Not Run)
	 76 - test_journaled_string_tree_find (Not Run)
```

**Comment by h-2** [comment]
ok, do you want me to go ahead and merge this or will you push other commits onto this branch?

**Comment by marehr** [comment]
I would prefer the merge, because the stuff I'm currently working in seqan3 on is depending on this.

I just wanted to give you a heads on that its not enabling c++17 for the whole library, but for most parts.

**Pull request merged**
