### PR TITLE
[DOC] Changed DfsPreorderIterator to DfsPreorder

### PR DESCRIPTION
**Pull request by s-cooper18**
Name fixed to be consistent with tag name present in code

### CODE REVIEW

**Comment by joergi-w** [comment]
I see that this PR is still open... 
@rrahn Can you please merge, if everything is fine?

**Comment by smehringer** [comment]
@s-cooper18 
Sorry that we are addressing this easy PR so late. Could you rebase onto the current develop? So you do not have the commit of rrahn in your PR. Then I'll merge this.

**Comment by rrahn** [comment]
@s-cooper18 sorry for the delay again, but even if it is small change it would be desirable to sign the CLA. 
If you think this is not worth it we might as well close the PR, but might fix it in a later iteration. But currently we are focussing all our strength on SeqAn3. Many thanks for your undertanding.

**Comment by smehringer** [comment]
@rrahn I think this can be merged?

**Pull request merged**
