### PR TITLE
performance degrade on windows

### LINKED ISSUE #1586: app_test_razers/app_test_stellar timeouts after 600s (performance degrade)
http://cdash.seqan.de/testDetails.php?test=31266148&build=169958

### PR DESCRIPTION
**Pull request by marehr**
Attempt to fix #1586.

The windows binaries are currently taking much more time than some days ago. After doing a bisect on windows, it seems to be related to the reverted commits in this pr. I'm not completely sure what is going on, but it seems that the generated build files for windows doesn't set the optimization flags as they should/as they did before.

### CODE REVIEW

**Comment by xenigmax** [comment]
I will merge this if continuous-integration works.

**Comment by xenigmax** [comment]
@marehr I manually rerun the nightly build on windows. So let's see what happens. If it resolves the failure, you should make another PR for develop branch :)

**Comment by marehr** [comment]
Ah! Thanks! :smirk_cat:

**Comment by xenigmax** [comment]
It seems work.
Thank you.

< 03/20 >
app_test_razers	Failed	10m 10ms	Completed (Timeout)


< Now (03/23) >
app_test_razers	Passed	28s 480ms	Completed

**Pull request merged**
