### PR TITLE
Partial fixes for -Wshorten-64-to-32

### PR DESCRIPTION
**Pull request by marehr**
See #710. Some changes to the code that warned about truncation.

### CODE REVIEW

**Comment by h-2** [comment]
@marehr please do not move things to the backlog. At the moment backlog basically means "TODO for SeqAn 3" which in the case is identical to just closing the PR. If it cannot be done for the upcoming release, move it to the next release instead.

**Comment by h-2** [comment]
@marehr If you can rebase the existing changes it would be great to merge it so that the work doesn't have to be re-done for SeqAn3.

**Comment by marehr** [comment]
My changes broke functionality as you can see on travis.  So the pr is not usable as it is. But  we could do some auditing and cherry-pick some parts of the current pr and make a new pr, that hopefully doesn't break anything.

**Comment by h-2** [comment]
> But we could do some auditing and cherry-pick some parts of the current pr and make a new pr, that hopefully doesn't break anything.

:+1:

**Comment by h-2** [comment]
@marehr ping

**Comment by h-2** [comment]
@marehr Please rebase the changes so I can merge them!

**Comment by marehr** [comment]
@h-2 this pr broke stuff, one of the reasons we never merged it.

**Comment by h-2** [comment]
Well you put a lot of work into it, it is your call whether we close this without merging, or whether you want to save some of it!

**Comment by marehr** [comment]
I broke stuff in between and it would require more work to find out which changes broke what than to simply start again. If someone wants to start again, he could use this pr as reference but with a salt of grain.

**Pull request closed without merging**
