### PR TITLE
Feature/add adapt stdarray

### PR DESCRIPTION
**Pull request by h-2**
add sequence interface for std::array (c++11)

### CODE REVIEW

**Comment by rrahn** [comment]
Why do we need this already for the 2.0.0 release?
Would it not be sufficient to use the String<TValue, Array<> > for the moment?
I mean we would have to discuss the things with the String class anyway for the future, so I wouldn't add more dependencies that are not necessary for the release?
Especially as there is no official C++-11 support for the library, is there?

**Comment by h-2** [comment]
it's a requirement for the blast module, but since that isn't going i we can postpone this, as well.

**Comment by esiragusa** [comment]
@h-2 why is the c++11 std::array required by the blast module? By the way, it seems to me that std::array should replace seqan::ArrayString.

**Comment by h-2** [comment]
> @h-2 why is the c++11 std::array required by the blast module? 

@esiragusa It was used for code-readability and convenience since c++11 is required anyway.

> By the way, it seems to me that std::array should replace seqan::ArrayString.

Just like the AllocString and std::string :stuck_out_tongue:

**Comment by esiragusa** [comment]
Okay then we'll have a look at it when you make a PR for the blast module.

**Comment by h-2** [comment]
@esiragusa or @rrahn please re-review.

**Comment by h-2** [comment]
superseded by #997

**Pull request closed without merging**
