### PR TITLE
merge master to develop post 2.3.2

### PR DESCRIPTION
**Pull request by smehringer**
Fixes PR #2041

### CODE REVIEW

**Comment by rrahn** [comment]
@smehringer Are we sure, that this was only an error for the PR? Not that we still have the same bug in Release? Can you quickly check this. Then I will merge. Thx a lot.

**Comment by smehringer** [comment]
@rrahn Yes, it was a bug unique to the PR. I double checked the file in the master branch. It must have happend due to merging.

**Comment by smehringer** [comment]
I signed the clahub already, but it seems to ignore me..

**Comment by rrahn** [comment]
Well, yeah this CLA plugin is somehow not working persistently. 😒

**Comment by h-2** [comment]
> Well, yeah this CLA plugin is somehow not working persistently. :unamused:

The clahub works correctly, but the PR contains a commit by @cpockrandt who hasn't signed so it's not supposed to greenlight.

**Pull request merged**
